name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Create executable
        run: |
          poetry run pyinstaller --onefile --windowed --name pdf-editor-${{ matrix.os }} app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-editor-${{ matrix.os }}
          path: dist/